#Generally designed with an idea of being cross compatible between compose and
#swarm mode.
version: '3.1'

services:
  #Our service.
  server:
    #we could've specified an image to use, but while developing we may want to always rebuild the
    #service since we are probably changing the code a lot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: 'auth-server'
    hostname: 'auth-server'
    #Mapping ports
    ports:
      # <port_on_local>:<port_in_machine>
      - "8000:8000"
    volumes:
      -  ./.env:/usr/bin/.env
  db:
      image: mongo
      container_name: db
      restart: on-failure
      ports:
          - "27017:27017"